// Package docsgen renders the Command line page of the documentation site
// from the real Cobra command tree, so the page can never describe a flag or
// a command that the binary does not have.
//
// It is a build-time tool, not part of the app: nothing under internal/app or
// internal/ui imports it, and the only caller is cmd/gendocs. The package
// works on a *cobra.Command it is handed and imports nothing from Devpit, so
// the command tree, the environment variable names and the page text all
// enter through arguments and the package stays trivial to test.
//
// The output is deterministic: commands are walked in Cobra's own sorted
// order and flags in pflag's, so regenerating with no source change produces
// no diff. A test in cmd/gendocs compares the committed page with a fresh
// render and fails when they differ.
package docsgen

import (
	"fmt"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

// notImplementedMarker is the phrase the reserved subcommands put at the end
// of their Short text (see cmd/devpit/stubs.go). The page turns it into a
// visible "not available yet" notice instead of printing it as part of the
// description, so a reader is told plainly what does nothing yet, and the
// notice disappears by itself when a command is implemented and the marker
// is dropped from its Short text.
const notImplementedMarker = " (not implemented yet)"

// EnvVar is one environment variable Devpit reads. The caller fills the list
// from the constants the packages that read them export, so the page and the
// code cannot name a different variable.
type EnvVar struct {
	// Name is the variable name, for example DEVPIT_NO_TELEMETRY.
	Name string
	// Effect says what setting it does, in one plain sentence.
	Effect string
}

// Options carries everything about the page that is not the command tree.
type Options struct {
	// Env lists the environment variables to document, in display order.
	Env []EnvVar
}

// Render returns the whole Markdown page, front matter included, for the
// command tree under root.
//
// It mutates root the same way running the real binary would: it asks Cobra
// to add the default help flag, the version flag and the completion command,
// because those exist for a user and belong on the page even though
// NewRootCmd does not create them itself.
func Render(root *cobra.Command, opts Options) string {
	root.InitDefaultHelpFlag()
	root.InitDefaultVersionFlag()
	root.InitDefaultCompletionCmd()

	var b strings.Builder
	b.WriteString(frontMatter)
	b.WriteString("\n")
	b.WriteString(intro)
	b.WriteString("\n")
	writeIndex(&b, root)
	writeCommand(&b, root, true)
	writeEnv(&b, opts.Env)
	return b.String()
}

// frontMatter is the page header. The description is fixed text rather than
// derived from the tree so the meta description never changes when a flag is
// added.
const frontMatter = `---
title: Command line reference
description: Every devpit command and flag, generated from the app itself. See and switch accounts, verify, undo, install the icon font and more from a terminal.
sidebar:
  label: Command line
related:
  - features/accounts
  - getting-started
  - safety-and-privacy
---

{/* GENERATED by "task docs:cli" (cmd/gendocs). Do not edit by hand. */}
`

// intro is the prose above the generated tables. It only states what is true
// of every build: the app opens with no arguments, and the subcommands are
// the scriptable side.
const intro = `Run ` + "`devpit`" + ` with no arguments to open the app. The commands below are for scripts, AI agents, the installer and quick checks.

This page is generated from the app's own command definitions, so it always matches the version you install.
`

// writeIndex writes the short list of commands at the top of the page, each
// linking to its section, so a reader can jump straight to one.
func writeIndex(b *strings.Builder, root *cobra.Command) {
	b.WriteString("## Commands\n\n")
	var walk func(c *cobra.Command)
	walk = func(c *cobra.Command) {
		for _, sub := range c.Commands() {
			if !sub.IsAvailableCommand() {
				continue
			}
			fmt.Fprintf(b, "- [`%s`](#%s): %s\n", sub.CommandPath(), anchor(sub.CommandPath()), plainShort(sub))
			walk(sub)
		}
	}
	fmt.Fprintf(b, "- [`%s`](#%s): %s\n", root.CommandPath(), anchor(root.CommandPath()), plainShort(root))
	walk(root)
	b.WriteString("\n")
}

// writeCommand writes the section for c and then, depth first, the sections
// of its available subcommands. isRoot changes only the wording: the root has
// no parent to inherit flags from.
func writeCommand(b *strings.Builder, c *cobra.Command, isRoot bool) {
	fmt.Fprintf(b, "## `%s`\n\n", c.CommandPath())

	if short, reserved := stripMarker(c.Short); short != "" {
		b.WriteString(escapeMDX(short) + ".\n\n")
		if reserved {
			b.WriteString(":::caution[Not available yet]\n")
			b.WriteString("This command is reserved and does nothing yet. Use the app instead: run `devpit` and pick the section.\n")
			b.WriteString(":::\n\n")
		}
	}
	if long := strings.TrimSpace(c.Long); long != "" && long != strings.TrimSpace(c.Short) && !isCompletion(c) {
		b.WriteString(escapeMDX(long) + "\n\n")
	}

	b.WriteString("```text\n" + c.UseLine() + "\n```\n\n")

	if flags := visibleFlags(c.LocalFlags()); len(flags) > 0 {
		b.WriteString("**Flags**\n\n")
		writeFlagTable(b, flags)
	}
	if !isRoot {
		if flags := visibleFlags(c.InheritedFlags()); len(flags) > 0 {
			b.WriteString("**Flags from `devpit`**\n\n")
			writeFlagTable(b, flags)
		}
	}
	if ex := strings.TrimSpace(c.Example); ex != "" {
		b.WriteString("**Examples**\n\n```powershell\n" + ex + "\n```\n\n")
	}
	if subs := availableSubs(c); len(subs) > 0 {
		b.WriteString("**Subcommands**\n\n")
		for _, sub := range subs {
			fmt.Fprintf(b, "- [`%s`](#%s): %s\n", sub.Name(), anchor(sub.CommandPath()), plainShort(sub))
		}
		b.WriteString("\n")
	}
	for _, sub := range availableSubs(c) {
		writeCommand(b, sub, false)
	}
}

// writeEnv writes the environment variable table, or nothing when the list
// is empty.
func writeEnv(b *strings.Builder, env []EnvVar) {
	if len(env) == 0 {
		return
	}
	b.WriteString("## Environment variables\n\n")
	b.WriteString("| Variable | What it does |\n| --- | --- |\n")
	for _, e := range env {
		fmt.Fprintf(b, "| `%s` | %s |\n", e.Name, cell(e.Effect))
	}
	b.WriteString("\n")
}

// writeFlagTable writes one Markdown table row per flag: the names, the
// value type, the default and the usage text.
func writeFlagTable(b *strings.Builder, flags []*pflag.Flag) {
	b.WriteString("| Flag | Type | Default | What it does |\n| --- | --- | --- | --- |\n")
	for _, f := range flags {
		names := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			names = "`-" + f.Shorthand + "`, " + names
		}
		def := f.DefValue
		if def == "" {
			def = "none"
		}
		fmt.Fprintf(b, "| %s | %s | `%s` | %s |\n", names, f.Value.Type(), def, cell(f.Usage))
	}
	b.WriteString("\n")
}

// visibleFlags returns the flags of fs a user is meant to see, in pflag's
// sorted order. Hidden flags (the elevated-helper pair) never reach the
// page: they are internal and documenting them would invite people to run
// them.
func visibleFlags(fs *pflag.FlagSet) []*pflag.Flag {
	var out []*pflag.Flag
	fs.VisitAll(func(f *pflag.Flag) {
		if !f.Hidden {
			out = append(out, f)
		}
	})
	return out
}

// availableSubs returns the subcommands of c a user can run, in Cobra's
// sorted order, leaving out hidden ones and Cobra's own help command.
func availableSubs(c *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, sub := range c.Commands() {
		if sub.IsAvailableCommand() {
			out = append(out, sub)
		}
	}
	return out
}

// isCompletion reports whether c is Cobra's built-in completion command or
// one of its per-shell children. Their long text is a generic install guide
// for Linux and macOS shells that Cobra writes for every program, which
// would bury Devpit's own commands on a page for a Windows app, so only
// their one-line descriptions and flags are kept.
func isCompletion(c *cobra.Command) bool {
	for p := c; p != nil; p = p.Parent() {
		if p.Name() == "completion" && p.HasParent() {
			return true
		}
	}
	return false
}

// stripMarker removes the "not implemented yet" marker from short and
// reports whether it was there. A trailing full stop is also removed so the
// caller can add exactly one.
func stripMarker(short string) (string, bool) {
	s := strings.TrimSpace(short)
	reserved := strings.HasSuffix(s, notImplementedMarker)
	s = strings.TrimSuffix(s, notImplementedMarker)
	return strings.TrimSuffix(s, "."), reserved
}

// plainShort is the one-line description used in lists: the Short text
// without the marker, and with a note appended when the command is reserved.
func plainShort(c *cobra.Command) string {
	short, reserved := stripMarker(c.Short)
	if reserved {
		return escapeMDX(short) + " (not available yet)"
	}
	return escapeMDX(short)
}

// anchor turns a command path into the heading id Starlight gives the
// section "## `devpit font install`": lower case, backticks dropped and
// spaces turned into hyphens.
func anchor(path string) string {
	return strings.ReplaceAll(strings.ToLower(path), " ", "-")
}

// cell makes text safe for one Markdown table cell: a pipe would end the
// cell and a newline would end the row.
func cell(s string) string {
	s = strings.ReplaceAll(s, "|", "\\|")
	return escapeMDX(strings.ReplaceAll(strings.TrimSpace(s), "\n", " "))
}

// escapeMDX protects the characters that MDX would read as JSX or an
// expression in text that came from Go string literals. The page is .mdx so
// the admonitions and the generated marker comment work, which makes braces
// and angle brackets in a command's long text a hazard.
func escapeMDX(s string) string {
	r := strings.NewReplacer("{", "\\{", "}", "\\}", "<", "&lt;")
	return r.Replace(s)
}
